# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebrtcIM' do

  pod 'MQTTClient', '~> 0.15.2'
  pod 'libjingle_peerconnection'

  target 'WebrtcIMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
